apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-vc-to-dwn
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: customer-vc-to-dwn
  template:
    metadata:
      labels:
        app: customer-vc-to-dwn
    spec:
      containers:
        - name: customer-vc-to-dwn
          image: "{{ .Values.customerVcToDwn.image.repository }}:{{ .Values.customerVcToDwn.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: customer-vc-to-dwn
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: customer-vc-to-dwn
      port: 5001
      targetPort: 5001
  selector:
    app: customer-vc-to-dwn