apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-vc-to-dwn-virtualservice1
spec:
  hosts:
    - "{{ .Values.virtualService.main }}"
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: customer-vc-to-dwn-route
      route:
        - destination:
            host: customer-vc-to-dwn
            port:
              number: 5001
---
# this lets app receive traffic from common ingress gateway
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: customer-vc-to-dwn-host
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - "{{ .Values.virtualService.main }}"
  - from:
    - source:
        namespaces: ["istio-system"]